#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileSiteDataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MobileSiteDatabase")]
	public partial class LinqToSqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertProductInformation(ProductInformation instance);
    partial void UpdateProductInformation(ProductInformation instance);
    partial void DeleteProductInformation(ProductInformation instance);
    #endregion
		
		public LinqToSqlDataContext() : 
				base(global::MobileSiteDataLayer.Properties.Settings.Default.MobileSiteDatabaseConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqToSqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ProductInformation> ProductInformations
		{
			get
			{
				return this.GetTable<ProductInformation>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProcGetLatestProducts")]
		public ISingleResult<ProcGetLatestProductsResult> ProcGetLatestProducts()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ProcGetLatestProductsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProcDeleteProduct")]
		public int ProcDeleteProduct([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> productId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProcGetProductPageDetails")]
		public ISingleResult<ProcGetProductPageDetailsResult> ProcGetProductPageDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> productId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productId);
			return ((ISingleResult<ProcGetProductPageDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProcInsertSiteUserCredentials")]
		public ISingleResult<ProcInsertSiteUserCredentialsResult> ProcInsertSiteUserCredentials([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="NVarChar(50)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="NVarChar(50)")] string lastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="NVarChar(50)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Country", DbType="NVarChar(50)")] string country, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactNumber", DbType="VarChar(50)")] string contactNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId, firstName, lastName, email, password, gender, country, contactNumber);
			return ((ISingleResult<ProcInsertSiteUserCredentialsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProcGetProductList")]
		public ISingleResult<ProcGetProductListResult> ProcGetProductList()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ProcGetProductListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProcInsertProducts")]
		public int ProcInsertProducts([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductName", DbType="NVarChar(50)")] string productName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SellingPrice", DbType="Decimal(18,3)")] System.Nullable<decimal> sellingPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MarketPrice", DbType="Decimal(18,3)")] System.Nullable<decimal> marketPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Stock", DbType="Decimal(18,0)")] System.Nullable<decimal> stock, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateOfInsert", DbType="Date")] System.Nullable<System.DateTime> dateOfInsert, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rating", DbType="Decimal(5,0)")] System.Nullable<decimal> rating, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OperatingSystem", DbType="NVarChar(50)")] string operatingSystem, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Color", DbType="NVarChar(50)")] string color, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsAvailable", DbType="Bit")] System.Nullable<bool> isAvailable, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstImage", DbType="NVarChar(50)")] string firstImage, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SecondImage", DbType="NVarChar(50)")] string secondImage, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ThirdImage", DbType="NVarChar(50)")] string thirdImage)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productId, productName, sellingPrice, marketPrice, stock, description, dateOfInsert, rating, operatingSystem, color, isAvailable, firstImage, secondImage, thirdImage);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProcGetProductData")]
		public ISingleResult<ProcGetProductDataResult> ProcGetProductData()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ProcGetProductDataResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.procGetAdminCredentials")]
		public ISingleResult<procGetAdminCredentialsResult> procGetAdminCredentials([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(50)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, password);
			return ((ISingleResult<procGetAdminCredentialsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProcGetProductListBulk")]
		public ISingleResult<ProcGetProductListBulkResult> ProcGetProductListBulk()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ProcGetProductListBulkResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.procGetSelectedFilters")]
		public ISingleResult<procGetSelectedFiltersResult> procGetSelectedFilters()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<procGetSelectedFiltersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.procDeleteSelectedFilters")]
		public ISingleResult<procDeleteSelectedFiltersResult> procDeleteSelectedFilters([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> filterId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), filterId);
			return ((ISingleResult<procDeleteSelectedFiltersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.procGetProductsBycolor")]
		public ISingleResult<procGetProductsBycolorResult> procGetProductsBycolor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string color, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string selectedFilter)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), color, selectedFilter);
			return ((ISingleResult<procGetProductsBycolorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.procIsBasketExisted")]
		public ISingleResult<procIsBasketExistedResult> procIsBasketExisted([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> userId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId);
			return ((ISingleResult<procIsBasketExistedResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProcGetLoginCredentials")]
		public ISingleResult<ProcGetLoginCredentialsResult> ProcGetLoginCredentials([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(50)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, password);
			return ((ISingleResult<ProcGetLoginCredentialsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.procGetUserBasketItems")]
		public ISingleResult<procGetUserBasketItemsResult> procGetUserBasketItems([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> userId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId);
			return ((ISingleResult<procGetUserBasketItemsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.procDeleteUserBasket")]
		public ISingleResult<procDeleteUserBasketResult> procDeleteUserBasket([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BasketHeaderId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> basketHeaderId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BasketLineId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> basketLineId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> productId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId, basketHeaderId, basketLineId, productId);
			return ((ISingleResult<procDeleteUserBasketResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProcInsertBasketItems")]
		public ISingleResult<ProcInsertBasketItemsResult> ProcInsertBasketItems([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Quantity", DbType="Int")] System.Nullable<int> quantity, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total", DbType="Decimal(10,2)")] System.Nullable<decimal> total, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BasketId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> basketId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BasketHeaderId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> basketHeaderId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="Decimal(12,2)")] System.Nullable<decimal> price, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StockCode", DbType="NVarChar(200)")] string stockCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productId, quantity, userId, total, basketId, basketHeaderId, price, stockCode);
			return ((ISingleResult<ProcInsertBasketItemsResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductInformation")]
	public partial class ProductInformation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ProductId;
		
		private string _ProductName;
		
		private System.Nullable<decimal> _SellingPrice;
		
		private System.Nullable<decimal> _MarketPrice;
		
		private System.Nullable<decimal> _Stock;
		
		private string _Description;
		
		private System.Nullable<System.DateTime> _DateOfInsert;
		
		private System.Nullable<decimal> _Rating;
		
		private string _OperatingSystem;
		
		private string _Color;
		
		private System.Nullable<bool> _IsAvailable;
		
		private string _FirstImage;
		
		private string _SecondImage;
		
		private string _ThirdImage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductIdChanging(System.Guid value);
    partial void OnProductIdChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    partial void OnSellingPriceChanging(System.Nullable<decimal> value);
    partial void OnSellingPriceChanged();
    partial void OnMarketPriceChanging(System.Nullable<decimal> value);
    partial void OnMarketPriceChanged();
    partial void OnStockChanging(System.Nullable<decimal> value);
    partial void OnStockChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnDateOfInsertChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfInsertChanged();
    partial void OnRatingChanging(System.Nullable<decimal> value);
    partial void OnRatingChanged();
    partial void OnOperatingSystemChanging(string value);
    partial void OnOperatingSystemChanged();
    partial void OnColorChanging(string value);
    partial void OnColorChanged();
    partial void OnIsAvailableChanging(System.Nullable<bool> value);
    partial void OnIsAvailableChanged();
    partial void OnFirstImageChanging(string value);
    partial void OnFirstImageChanged();
    partial void OnSecondImageChanging(string value);
    partial void OnSecondImageChanged();
    partial void OnThirdImageChanging(string value);
    partial void OnThirdImageChanged();
    #endregion
		
		public ProductInformation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="NVarChar(50)")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this.OnProductNameChanging(value);
					this.SendPropertyChanging();
					this._ProductName = value;
					this.SendPropertyChanged("ProductName");
					this.OnProductNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellingPrice", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> SellingPrice
		{
			get
			{
				return this._SellingPrice;
			}
			set
			{
				if ((this._SellingPrice != value))
				{
					this.OnSellingPriceChanging(value);
					this.SendPropertyChanging();
					this._SellingPrice = value;
					this.SendPropertyChanged("SellingPrice");
					this.OnSellingPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarketPrice", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> MarketPrice
		{
			get
			{
				return this._MarketPrice;
			}
			set
			{
				if ((this._MarketPrice != value))
				{
					this.OnMarketPriceChanging(value);
					this.SendPropertyChanging();
					this._MarketPrice = value;
					this.SendPropertyChanged("MarketPrice");
					this.OnMarketPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stock", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Stock
		{
			get
			{
				return this._Stock;
			}
			set
			{
				if ((this._Stock != value))
				{
					this.OnStockChanging(value);
					this.SendPropertyChanging();
					this._Stock = value;
					this.SendPropertyChanged("Stock");
					this.OnStockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfInsert", DbType="Date")]
		public System.Nullable<System.DateTime> DateOfInsert
		{
			get
			{
				return this._DateOfInsert;
			}
			set
			{
				if ((this._DateOfInsert != value))
				{
					this.OnDateOfInsertChanging(value);
					this.SendPropertyChanging();
					this._DateOfInsert = value;
					this.SendPropertyChanged("DateOfInsert");
					this.OnDateOfInsertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Decimal(5,0)")]
		public System.Nullable<decimal> Rating
		{
			get
			{
				return this._Rating;
			}
			set
			{
				if ((this._Rating != value))
				{
					this.OnRatingChanging(value);
					this.SendPropertyChanging();
					this._Rating = value;
					this.SendPropertyChanged("Rating");
					this.OnRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatingSystem", DbType="NVarChar(50)")]
		public string OperatingSystem
		{
			get
			{
				return this._OperatingSystem;
			}
			set
			{
				if ((this._OperatingSystem != value))
				{
					this.OnOperatingSystemChanging(value);
					this.SendPropertyChanging();
					this._OperatingSystem = value;
					this.SendPropertyChanged("OperatingSystem");
					this.OnOperatingSystemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="NVarChar(50)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this.OnColorChanging(value);
					this.SendPropertyChanging();
					this._Color = value;
					this.SendPropertyChanged("Color");
					this.OnColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAvailable", DbType="Bit")]
		public System.Nullable<bool> IsAvailable
		{
			get
			{
				return this._IsAvailable;
			}
			set
			{
				if ((this._IsAvailable != value))
				{
					this.OnIsAvailableChanging(value);
					this.SendPropertyChanging();
					this._IsAvailable = value;
					this.SendPropertyChanged("IsAvailable");
					this.OnIsAvailableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstImage", DbType="NVarChar(50)")]
		public string FirstImage
		{
			get
			{
				return this._FirstImage;
			}
			set
			{
				if ((this._FirstImage != value))
				{
					this.OnFirstImageChanging(value);
					this.SendPropertyChanging();
					this._FirstImage = value;
					this.SendPropertyChanged("FirstImage");
					this.OnFirstImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondImage", DbType="NVarChar(50)")]
		public string SecondImage
		{
			get
			{
				return this._SecondImage;
			}
			set
			{
				if ((this._SecondImage != value))
				{
					this.OnSecondImageChanging(value);
					this.SendPropertyChanging();
					this._SecondImage = value;
					this.SendPropertyChanged("SecondImage");
					this.OnSecondImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThirdImage", DbType="NVarChar(50)")]
		public string ThirdImage
		{
			get
			{
				return this._ThirdImage;
			}
			set
			{
				if ((this._ThirdImage != value))
				{
					this.OnThirdImageChanging(value);
					this.SendPropertyChanging();
					this._ThirdImage = value;
					this.SendPropertyChanged("ThirdImage");
					this.OnThirdImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class ProcGetLatestProductsResult
	{
		
		private System.Guid _ProductId;
		
		private string _ProductName;
		
		private System.Nullable<decimal> _SellingPrice;
		
		private string _OperatingSystem;
		
		private string _SecondImage;
		
		public ProcGetLatestProductsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this._ProductId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="NVarChar(50)")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellingPrice", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> SellingPrice
		{
			get
			{
				return this._SellingPrice;
			}
			set
			{
				if ((this._SellingPrice != value))
				{
					this._SellingPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatingSystem", DbType="NVarChar(50)")]
		public string OperatingSystem
		{
			get
			{
				return this._OperatingSystem;
			}
			set
			{
				if ((this._OperatingSystem != value))
				{
					this._OperatingSystem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondImage", DbType="NVarChar(50)")]
		public string SecondImage
		{
			get
			{
				return this._SecondImage;
			}
			set
			{
				if ((this._SecondImage != value))
				{
					this._SecondImage = value;
				}
			}
		}
	}
	
	public partial class ProcGetProductPageDetailsResult
	{
		
		private System.Guid _ProductId;
		
		private string _ProductName;
		
		private System.Nullable<decimal> _SellingPrice;
		
		private string _Color;
		
		private string _OperatingSystem;
		
		private System.Nullable<decimal> _Rating;
		
		private string _SecondImage;
		
		private string _Description;
		
		public ProcGetProductPageDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this._ProductId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="NVarChar(50)")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellingPrice", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> SellingPrice
		{
			get
			{
				return this._SellingPrice;
			}
			set
			{
				if ((this._SellingPrice != value))
				{
					this._SellingPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="NVarChar(50)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatingSystem", DbType="NVarChar(50)")]
		public string OperatingSystem
		{
			get
			{
				return this._OperatingSystem;
			}
			set
			{
				if ((this._OperatingSystem != value))
				{
					this._OperatingSystem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Decimal(5,0)")]
		public System.Nullable<decimal> Rating
		{
			get
			{
				return this._Rating;
			}
			set
			{
				if ((this._Rating != value))
				{
					this._Rating = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondImage", DbType="NVarChar(50)")]
		public string SecondImage
		{
			get
			{
				return this._SecondImage;
			}
			set
			{
				if ((this._SecondImage != value))
				{
					this._SecondImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
	
	public partial class ProcInsertSiteUserCredentialsResult
	{
		
		private System.Nullable<bool> _isValid;
		
		private string _Message;
		
		public ProcInsertSiteUserCredentialsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isValid", DbType="Bit")]
		public System.Nullable<bool> isValid
		{
			get
			{
				return this._isValid;
			}
			set
			{
				if ((this._isValid != value))
				{
					this._isValid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NVarChar(200)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this._Message = value;
				}
			}
		}
	}
	
	public partial class ProcGetProductListResult
	{
		
		private string _ProductName;
		
		private System.Nullable<decimal> _SellingPrice;
		
		private string _OperatingSystem;
		
		private string _SecondImage;
		
		public ProcGetProductListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="NVarChar(50)")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellingPrice", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> SellingPrice
		{
			get
			{
				return this._SellingPrice;
			}
			set
			{
				if ((this._SellingPrice != value))
				{
					this._SellingPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatingSystem", DbType="NVarChar(50)")]
		public string OperatingSystem
		{
			get
			{
				return this._OperatingSystem;
			}
			set
			{
				if ((this._OperatingSystem != value))
				{
					this._OperatingSystem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondImage", DbType="NVarChar(50)")]
		public string SecondImage
		{
			get
			{
				return this._SecondImage;
			}
			set
			{
				if ((this._SecondImage != value))
				{
					this._SecondImage = value;
				}
			}
		}
	}
	
	public partial class ProcGetProductDataResult
	{
		
		private System.Guid _ProductId;
		
		private string _ProductName;
		
		private System.Nullable<decimal> _SellingPrice;
		
		private System.Nullable<decimal> _MarketPrice;
		
		private System.Nullable<decimal> _Stock;
		
		private string _Description;
		
		private System.Nullable<System.DateTime> _DateOfInsert;
		
		private System.Nullable<decimal> _Rating;
		
		private string _OperatingSystem;
		
		private string _Color;
		
		private System.Nullable<bool> _IsAvailable;
		
		private string _FirstImage;
		
		private string _SecondImage;
		
		private string _ThirdImage;
		
		public ProcGetProductDataResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this._ProductId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="NVarChar(50)")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellingPrice", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> SellingPrice
		{
			get
			{
				return this._SellingPrice;
			}
			set
			{
				if ((this._SellingPrice != value))
				{
					this._SellingPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarketPrice", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> MarketPrice
		{
			get
			{
				return this._MarketPrice;
			}
			set
			{
				if ((this._MarketPrice != value))
				{
					this._MarketPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stock", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Stock
		{
			get
			{
				return this._Stock;
			}
			set
			{
				if ((this._Stock != value))
				{
					this._Stock = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfInsert", DbType="Date")]
		public System.Nullable<System.DateTime> DateOfInsert
		{
			get
			{
				return this._DateOfInsert;
			}
			set
			{
				if ((this._DateOfInsert != value))
				{
					this._DateOfInsert = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Decimal(5,0)")]
		public System.Nullable<decimal> Rating
		{
			get
			{
				return this._Rating;
			}
			set
			{
				if ((this._Rating != value))
				{
					this._Rating = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatingSystem", DbType="NVarChar(50)")]
		public string OperatingSystem
		{
			get
			{
				return this._OperatingSystem;
			}
			set
			{
				if ((this._OperatingSystem != value))
				{
					this._OperatingSystem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="NVarChar(50)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAvailable", DbType="Bit")]
		public System.Nullable<bool> IsAvailable
		{
			get
			{
				return this._IsAvailable;
			}
			set
			{
				if ((this._IsAvailable != value))
				{
					this._IsAvailable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstImage", DbType="NVarChar(50)")]
		public string FirstImage
		{
			get
			{
				return this._FirstImage;
			}
			set
			{
				if ((this._FirstImage != value))
				{
					this._FirstImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondImage", DbType="NVarChar(50)")]
		public string SecondImage
		{
			get
			{
				return this._SecondImage;
			}
			set
			{
				if ((this._SecondImage != value))
				{
					this._SecondImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThirdImage", DbType="NVarChar(50)")]
		public string ThirdImage
		{
			get
			{
				return this._ThirdImage;
			}
			set
			{
				if ((this._ThirdImage != value))
				{
					this._ThirdImage = value;
				}
			}
		}
	}
	
	public partial class procGetAdminCredentialsResult
	{
		
		private System.Nullable<bool> _isvalid;
		
		private string _Message;
		
		public procGetAdminCredentialsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isvalid", DbType="Bit")]
		public System.Nullable<bool> isvalid
		{
			get
			{
				return this._isvalid;
			}
			set
			{
				if ((this._isvalid != value))
				{
					this._isvalid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NVarChar(200)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this._Message = value;
				}
			}
		}
	}
	
	public partial class ProcGetProductListBulkResult
	{
		
		private System.Guid _ProductId;
		
		private string _ProductName;
		
		private System.Nullable<decimal> _SellingPrice;
		
		private string _OperatingSystem;
		
		private string _SecondImage;
		
		private string _Description;
		
		private System.Nullable<decimal> _Rating;
		
		public ProcGetProductListBulkResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this._ProductId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="NVarChar(50)")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellingPrice", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> SellingPrice
		{
			get
			{
				return this._SellingPrice;
			}
			set
			{
				if ((this._SellingPrice != value))
				{
					this._SellingPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatingSystem", DbType="NVarChar(50)")]
		public string OperatingSystem
		{
			get
			{
				return this._OperatingSystem;
			}
			set
			{
				if ((this._OperatingSystem != value))
				{
					this._OperatingSystem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondImage", DbType="NVarChar(50)")]
		public string SecondImage
		{
			get
			{
				return this._SecondImage;
			}
			set
			{
				if ((this._SecondImage != value))
				{
					this._SecondImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Decimal(5,0)")]
		public System.Nullable<decimal> Rating
		{
			get
			{
				return this._Rating;
			}
			set
			{
				if ((this._Rating != value))
				{
					this._Rating = value;
				}
			}
		}
	}
	
	public partial class procGetSelectedFiltersResult
	{
		
		private System.Guid _Id;
		
		private string _filtername;
		
		private string _filterType;
		
		public procGetSelectedFiltersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filtername", DbType="NVarChar(50)")]
		public string filtername
		{
			get
			{
				return this._filtername;
			}
			set
			{
				if ((this._filtername != value))
				{
					this._filtername = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filterType", DbType="NVarChar(50)")]
		public string filterType
		{
			get
			{
				return this._filterType;
			}
			set
			{
				if ((this._filterType != value))
				{
					this._filterType = value;
				}
			}
		}
	}
	
	public partial class procDeleteSelectedFiltersResult
	{
		
		private System.Nullable<bool> _IsValid;
		
		public procDeleteSelectedFiltersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsValid", DbType="Bit")]
		public System.Nullable<bool> IsValid
		{
			get
			{
				return this._IsValid;
			}
			set
			{
				if ((this._IsValid != value))
				{
					this._IsValid = value;
				}
			}
		}
	}
	
	public partial class procGetProductsBycolorResult
	{
		
		private System.Guid _ProductId;
		
		private string _ProductName;
		
		private System.Nullable<decimal> _SellingPrice;
		
		private string _OperatingSystem;
		
		private string _SecondImage;
		
		private string _Description;
		
		private System.Nullable<decimal> _Rating;
		
		private string _Color;
		
		public procGetProductsBycolorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this._ProductId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="NVarChar(50)")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellingPrice", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> SellingPrice
		{
			get
			{
				return this._SellingPrice;
			}
			set
			{
				if ((this._SellingPrice != value))
				{
					this._SellingPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatingSystem", DbType="NVarChar(50)")]
		public string OperatingSystem
		{
			get
			{
				return this._OperatingSystem;
			}
			set
			{
				if ((this._OperatingSystem != value))
				{
					this._OperatingSystem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondImage", DbType="NVarChar(50)")]
		public string SecondImage
		{
			get
			{
				return this._SecondImage;
			}
			set
			{
				if ((this._SecondImage != value))
				{
					this._SecondImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Decimal(5,0)")]
		public System.Nullable<decimal> Rating
		{
			get
			{
				return this._Rating;
			}
			set
			{
				if ((this._Rating != value))
				{
					this._Rating = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="NVarChar(50)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
	}
	
	public partial class procIsBasketExistedResult
	{
		
		private System.Nullable<System.Guid> _Id;
		
		private System.Nullable<bool> _IsExisted;
		
		public procIsBasketExistedResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsExisted", DbType="Bit")]
		public System.Nullable<bool> IsExisted
		{
			get
			{
				return this._IsExisted;
			}
			set
			{
				if ((this._IsExisted != value))
				{
					this._IsExisted = value;
				}
			}
		}
	}
	
	public partial class ProcGetLoginCredentialsResult
	{
		
		private System.Nullable<bool> _IsValid;
		
		private string _Message;
		
		private System.Nullable<System.Guid> _UserId;
		
		private string _FirstName;
		
		public ProcGetLoginCredentialsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsValid", DbType="Bit")]
		public System.Nullable<bool> IsValid
		{
			get
			{
				return this._IsValid;
			}
			set
			{
				if ((this._IsValid != value))
				{
					this._IsValid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NVarChar(200)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this._Message = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(200)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
	}
	
	public partial class procGetUserBasketItemsResult
	{
		
		private System.Nullable<System.Guid> _ProductId;
		
		private string _ProductName;
		
		private System.Nullable<int> _Quantity;
		
		private System.Nullable<decimal> _Price;
		
		private string _SecondImage;
		
		private System.Nullable<System.Guid> _BaketHeaderId;
		
		private string _Description;
		
		private System.Nullable<int> _Total;
		
		private System.Nullable<System.Guid> _Id;
		
		public procGetUserBasketItemsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this._ProductId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="NVarChar(50)")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int")]
		public System.Nullable<int> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondImage", DbType="NVarChar(50)")]
		public string SecondImage
		{
			get
			{
				return this._SecondImage;
			}
			set
			{
				if ((this._SecondImage != value))
				{
					this._SecondImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaketHeaderId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> BaketHeaderId
		{
			get
			{
				return this._BaketHeaderId;
			}
			set
			{
				if ((this._BaketHeaderId != value))
				{
					this._BaketHeaderId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
	
	public partial class procDeleteUserBasketResult
	{
		
		private System.Nullable<bool> _IsValid;
		
		public procDeleteUserBasketResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsValid", DbType="Bit")]
		public System.Nullable<bool> IsValid
		{
			get
			{
				return this._IsValid;
			}
			set
			{
				if ((this._IsValid != value))
				{
					this._IsValid = value;
				}
			}
		}
	}
	
	public partial class ProcInsertBasketItemsResult
	{
		
		private System.Nullable<System.Guid> _BasketId;
		
		public ProcInsertBasketItemsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasketId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> BasketId
		{
			get
			{
				return this._BasketId;
			}
			set
			{
				if ((this._BasketId != value))
				{
					this._BasketId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
